"""delivery 3 conversational persistence

Revision ID: 20260731_0002
Revises: 20260731_0001
Create Date: 2026-07-31 13:28:01.842210
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260731_0002"
down_revision: str | None = "20260731_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_SETTING = "NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
TENANT_TABLES = (
    "contacts",
    "leads",
    "conversations",
    "conversation_messages",
    "message_processing",
    "extraction_executions",
    "lead_profile_values",
    "lead_profile_conflicts",
    "lead_commercial_signals",
    "qualification_evaluations",
    "contact_preferences",
    "handoff_requests",
    "pending_questions",
    "conversation_outbox_events",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("normalized_phone", sa.String(length=20), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("preference", sa.String(length=30), nullable=False),
        sa.Column("do_not_contact", sa.Boolean(), nullable=False),
        sa.Column("dnc_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(do_not_contact AND preference = 'do_not_contact' AND dnc_recorded_at IS NOT NULL) OR (NOT do_not_contact AND preference <> 'do_not_contact')",
            name="ck_contacts_dnc_consistency",
        ),
        sa.CheckConstraint(
            "channel IN ('internal', 'whatsapp', 'sms', 'webchat')", name="ck_contacts_channel"
        ),
        sa.CheckConstraint("kind IN ('individual', 'business')", name="ck_contacts_kind"),
        sa.CheckConstraint(
            "preference IN ('unspecified', 'automated_allowed', 'human_only', 'do_not_contact')",
            name="ck_contacts_preference",
        ),
        sa.CheckConstraint("version > 0", name="ck_contacts_version"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_contacts_tenant"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "channel", "external_id", name="uq_contacts_external"),
    )
    op.create_table(
        "conversation_outbox_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=60), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name="ck_conversation_outbox_payload"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'publishing', 'retry', 'published', 'dead')",
            name="ck_conversation_outbox_status",
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL AND lease_until IS NULL) OR (lease_token IS NOT NULL AND lease_until IS NOT NULL)",
            name="ck_conversation_outbox_lease",
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_conversation_outbox_attempts"),
        sa.CheckConstraint("char_length(payload_hash) = 64", name="ck_conversation_outbox_hash"),
        sa.CheckConstraint("payload_version > 0", name="ck_conversation_outbox_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_conversation_outbox_tenant"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "event_key", name="uq_conversation_outbox_event_key"),
    )
    op.create_index(
        "ix_conversation_outbox_claim",
        "conversation_outbox_events",
        ["status", "next_attempt_at", "lease_until"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("primary_opportunity", sa.String(length=40), nullable=False),
        sa.Column(
            "secondary_opportunities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("current_evaluation_id", sa.UUID(), nullable=True),
        sa.Column("current_score", sa.Integer(), nullable=True),
        sa.Column("current_classification", sa.String(length=20), nullable=True),
        sa.Column("current_policy_id", sa.UUID(), nullable=True),
        sa.Column("current_policy_version", sa.Integer(), nullable=True),
        sa.Column("current_policy_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("eligibility", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(secondary_opportunities) = 'array'", name="ck_leads_secondary_array"
        ),
        sa.CheckConstraint(
            "primary_opportunity IN ('device_purchase', 'device_with_plan', 'plan_subscription', 'new_line', 'portability', 'renewal', 'prepaid_to_postpaid', 'accessory', 'multiple_lines', 'business_account', 'unidentified')",
            name="ck_leads_primary_opportunity",
        ),
        sa.CheckConstraint(
            "state IN ('new', 'in_conversation', 'qualifying', 'incomplete_information', 'qualified', 'quote_requested', 'quote_sent', 'pending_documents', 'pending_validation', 'pending_inventory', 'pending_coverage', 'pending_financing', 'transferred_to_advisor', 'contacted_by_advisor', 'portability_started', 'contracting_started', 'sale_completed', 'lost', 'not_eligible', 'duplicate', 'do_not_contact')",
            name="ck_leads_state",
        ),
        sa.CheckConstraint(
            "(current_evaluation_id IS NULL AND current_score IS NULL AND current_classification IS NULL AND current_policy_id IS NULL AND current_policy_version IS NULL AND current_policy_fingerprint IS NULL) OR (current_evaluation_id IS NOT NULL AND current_score IS NOT NULL AND current_classification IS NOT NULL AND current_policy_id IS NOT NULL AND current_policy_version IS NOT NULL AND current_policy_fingerprint IS NOT NULL)",
            name="ck_leads_evaluation_consistency",
        ),
        sa.CheckConstraint(
            "current_score IS NULL OR current_score BETWEEN 0 AND 100",
            name="ck_leads_current_score",
        ),
        sa.CheckConstraint("version > 0", name="ck_leads_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
            name="fk_leads_contact",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_leads_tenant"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "id", "contact_id", name="uq_leads_id_contact"),
    )
    op.create_table(
        "conversations",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("automation_active", sa.Boolean(), nullable=False),
        sa.Column("human_owner_id", sa.String(length=120), nullable=True),
        sa.Column("last_message_id", sa.UUID(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commercial_summary", sa.String(length=2000), nullable=True),
        sa.Column("processing_message_id", sa.UUID(), nullable=True),
        sa.Column("processing_lease_token", sa.UUID(), nullable=True),
        sa.Column("processing_lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(state = 'closed' AND closed_at IS NOT NULL) OR (state <> 'closed' AND closed_at IS NULL)",
            name="ck_conversations_closed_at",
        ),
        sa.CheckConstraint(
            "channel IN ('internal', 'whatsapp', 'sms', 'webchat')", name="ck_conversations_channel"
        ),
        sa.CheckConstraint(
            "state IN ('open', 'qualifying', 'waiting_customer', 'waiting_human', 'human_active', 'automated_paused', 'do_not_contact', 'closed')",
            name="ck_conversations_state",
        ),
        sa.CheckConstraint(
            "state NOT IN ('waiting_human', 'human_active', 'automated_paused', 'do_not_contact', 'closed') OR NOT automation_active",
            name="ck_conversations_automation_state",
        ),
        sa.CheckConstraint(
            "(processing_message_id IS NULL AND processing_lease_token IS NULL AND processing_lease_until IS NULL) OR (processing_message_id IS NOT NULL AND processing_lease_token IS NOT NULL AND processing_lease_until IS NOT NULL)",
            name="ck_conversations_processing_lease",
        ),
        sa.CheckConstraint("version > 0", name="ck_conversations_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
            name="fk_conversations_contact",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id", "contact_id"],
            ["leads.tenant_id", "leads.id", "leads.contact_id"],
            name="fk_conversations_lead_contact",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_conversations_tenant"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint(
            "tenant_id", "channel", "external_id", name="uq_conversations_external"
        ),
        sa.UniqueConstraint("tenant_id", "id", "channel", name="uq_conversations_id_channel"),
        sa.UniqueConstraint(
            "tenant_id", "id", "contact_id", "lead_id", name="uq_conversations_identity"
        ),
        sa.UniqueConstraint("tenant_id", "id", "lead_id", name="uq_conversations_id_lead"),
    )
    op.create_table(
        "conversation_messages",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("external_message_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("author", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("external_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_status", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(direction = 'inbound' AND author = 'customer') OR (direction = 'outbound' AND author <> 'customer')",
            name="ck_conversation_messages_author_direction",
        ),
        sa.CheckConstraint(
            "author IN ('customer', 'system', 'human_advisor')",
            name="ck_conversation_messages_author",
        ),
        sa.CheckConstraint("content_type = 'text'", name="ck_conversation_messages_content_type"),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound')", name="ck_conversation_messages_direction"
        ),
        sa.CheckConstraint("jsonb_typeof(metadata) = 'object'", name="ck_messages_metadata_object"),
        sa.CheckConstraint(
            "processing_status IN ('pending', 'processing', 'completed', 'completed_degraded', 'blocked_do_not_contact', 'blocked_handoff', 'retryable_failure', 'permanent_failure', 'invalid_extraction')",
            name="ck_conversation_messages_processing_status",
        ),
        sa.CheckConstraint(
            "char_length(content) BETWEEN 1 AND 20000",
            name="ck_conversation_messages_content_length",
        ),
        sa.CheckConstraint("char_length(fingerprint) = 64", name="ck_messages_fingerprint"),
        sa.CheckConstraint("char_length(idempotency_key) = 64", name="ck_messages_idempotency"),
        sa.CheckConstraint("version > 0", name="ck_conversation_messages_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id", "channel"],
            ["conversations.tenant_id", "conversations.id", "conversations.channel"],
            name="fk_conversation_messages_conversation",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint(
            "tenant_id",
            "channel",
            "external_message_id",
            "event_type",
            name="uq_conversation_messages_external",
        ),
        sa.UniqueConstraint(
            "tenant_id", "id", "conversation_id", name="uq_conversation_messages_identity"
        ),
    )
    op.create_index(
        "ix_conversation_messages_timeline",
        "conversation_messages",
        ["tenant_id", "conversation_id", "external_timestamp"],
        unique=False,
    )
    op.create_table(
        "message_processing",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("processing_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=True),
        sa.Column("evaluation_id", sa.UUID(), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'completed_degraded', 'blocked_do_not_contact', 'blocked_handoff', 'retryable_failure', 'permanent_failure', 'invalid_extraction')",
            name="ck_message_processing_status",
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL AND lease_until IS NULL) OR (lease_token IS NOT NULL AND lease_until IS NOT NULL)",
            name="ck_message_processing_lease",
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_message_processing_attempts"),
        sa.CheckConstraint("processing_version > 0", name="ck_message_processing_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "message_id", "conversation_id"],
            [
                "conversation_messages.tenant_id",
                "conversation_messages.id",
                "conversation_messages.conversation_id",
            ],
            name="fk_message_processing_message",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "id", "message_id", name="uq_message_processing_identity"),
        sa.UniqueConstraint(
            "tenant_id", "message_id", "processing_version", name="uq_message_processing_version"
        ),
    )
    op.create_index(
        "ix_message_processing_claim",
        "message_processing",
        ["status", "next_attempt_at", "lease_until"],
        unique=False,
    )
    op.create_table(
        "extraction_executions",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("processing_id", sa.UUID(), nullable=False),
        sa.Column("processing_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("conceptual_key", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("result_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("accepted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(accepted_payload) = 'object'", name="ck_extraction_payload"
        ),
        sa.CheckConstraint("jsonb_typeof(failures) = 'array'", name="ck_extraction_failures"),
        sa.CheckConstraint("jsonb_typeof(warnings) = 'array'", name="ck_extraction_warnings"),
        sa.CheckConstraint("outcome IN ('completed', 'degraded')", name="ck_extraction_outcome"),
        sa.CheckConstraint(
            "status IN ('completed', 'degraded', 'invalid', 'failed')", name="ck_extraction_status"
        ),
        sa.CheckConstraint(
            "estimated_cost_usd IS NULL OR estimated_cost_usd >= 0", name="ck_extraction_cost"
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND latency_ms >= 0",
            name="ck_extraction_usage",
        ),
        sa.CheckConstraint("processing_version > 0", name="ck_extraction_processing_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id", "lead_id"],
            ["conversations.tenant_id", "conversations.id", "conversations.lead_id"],
            name="fk_extraction_conversation_lead",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "message_id", "conversation_id"],
            [
                "conversation_messages.tenant_id",
                "conversation_messages.id",
                "conversation_messages.conversation_id",
            ],
            name="fk_extraction_message",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "processing_id", "message_id"],
            [
                "message_processing.tenant_id",
                "message_processing.id",
                "message_processing.message_id",
            ],
            name="fk_extraction_processing",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "id", "lead_id", name="uq_extraction_id_lead"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_extraction_executions_key"),
        sa.UniqueConstraint("tenant_id", "processing_id", name="uq_extraction_processing"),
    )
    op.create_table(
        "contact_preferences",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("preference_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_message_id", sa.UUID(), nullable=False),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("evidence_code", sa.String(length=100), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=120), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(status = 'active' AND revoked_at IS NULL AND revoked_by IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by IS NOT NULL)",
            name="ck_contact_preferences_revocation",
        ),
        sa.CheckConstraint(
            "preference_type = 'do_not_contact'", name="ck_contact_preferences_type"
        ),
        sa.CheckConstraint("status IN ('active', 'revoked')", name="ck_contact_preferences_status"),
        sa.CheckConstraint("char_length(evidence_hash) = 64", name="ck_contact_preferences_hash"),
        sa.CheckConstraint("version > 0", name="ck_contact_preferences_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id", "contact_id", "lead_id"],
            [
                "conversations.tenant_id",
                "conversations.id",
                "conversations.contact_id",
                "conversations.lead_id",
            ],
            name="fk_contact_preferences_conversation",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_contact_preferences_extraction",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_message_id", "conversation_id"],
            [
                "conversation_messages.tenant_id",
                "conversation_messages.id",
                "conversation_messages.conversation_id",
            ],
            name="fk_contact_preferences_message",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_index(
        "uq_contact_preferences_active",
        "contact_preferences",
        ["tenant_id", "contact_id", "preference_type"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "handoff_requests",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.String(length=120), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(missing_information) = 'array'", name="ck_handoff_requests_missing"
        ),
        sa.CheckConstraint("kind IN ('general', 'specialized')", name="ck_handoff_requests_kind"),
        sa.CheckConstraint(
            "source IN ('customer', 'extraction', 'scoring')", name="ck_handoff_requests_source"
        ),
        sa.CheckConstraint(
            "status IN ('requested', 'queued', 'assigned', 'accepted', 'resolved', 'cancelled', 'expired')",
            name="ck_handoff_requests_status",
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 1000", name="ck_handoff_requests_priority"),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_handoff_requests_score"),
        sa.CheckConstraint("version > 0", name="ck_handoff_requests_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id", "lead_id"],
            ["conversations.tenant_id", "conversations.id", "conversations.lead_id"],
            name="fk_handoff_requests_conversation",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_handoff_requests_extraction",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint(
            "tenant_id", "id", "conversation_id", name="uq_handoff_requests_identity"
        ),
    )
    op.create_index(
        "uq_handoff_requests_active",
        "handoff_requests",
        ["tenant_id", "conversation_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('requested', 'queued', 'assigned', 'accepted')"),
    )
    op.create_table(
        "lead_commercial_signals",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("extraction_method", sa.String(length=20), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("application_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "extraction_method IN ('explicit', 'ai', 'human', 'system', 'import')",
            name="ck_commercial_signals_method",
        ),
        sa.CheckConstraint(
            "validation_status IN ('hypothesis', 'accepted', 'confirmed', 'rejected')",
            name="ck_commercial_signals_status",
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_commercial_signals_confidence"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_commercial_signals_extraction",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"],
            ["leads.tenant_id", "leads.id"],
            name="fk_commercial_signals_lead",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_message_id"],
            ["conversation_messages.tenant_id", "conversation_messages.id"],
            name="fk_commercial_signals_message",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint(
            "tenant_id", "application_key", name="uq_commercial_signals_application"
        ),
    )
    op.create_index(
        "ix_commercial_signals_active",
        "lead_commercial_signals",
        ["tenant_id", "lead_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "lead_profile_values",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=80), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("value_hash", sa.String(length=64), nullable=False),
        sa.Column("application_key", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_by", sa.String(length=120), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("support_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "source IN ('customer', 'system_lookup', 'human_advisor', 'import')",
            name="ck_profile_source",
        ),
        sa.CheckConstraint(
            "validation_status IN ('hypothesis', 'accepted', 'confirmed', 'rejected')",
            name="ck_profile_validation_status",
        ),
        sa.CheckConstraint(
            "value_type IN ('string', 'integer', 'boolean', 'decimal')",
            name="ck_profile_value_type",
        ),
        sa.CheckConstraint(
            "(is_current AND valid_to IS NULL) OR (NOT is_current)",
            name="ck_profile_current_validity",
        ),
        sa.CheckConstraint("char_length(application_key) = 64", name="ck_profile_application_key"),
        sa.CheckConstraint("char_length(value_hash) = 64", name="ck_profile_value_hash"),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_profile_confidence"),
        sa.CheckConstraint("support_count > 0", name="ck_profile_support_count"),
        sa.CheckConstraint("version > 0", name="ck_profile_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_profile_values_extraction",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "lead_id"], ["leads.tenant_id", "leads.id"], name="fk_profile_values_lead"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_message_id"],
            ["conversation_messages.tenant_id", "conversation_messages.id"],
            name="fk_profile_values_message",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "application_key", name="uq_profile_values_application"),
        sa.UniqueConstraint("tenant_id", "id", "lead_id", name="uq_profile_values_identity"),
    )
    op.create_index(
        "ix_profile_values_history",
        "lead_profile_values",
        ["tenant_id", "lead_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "uq_profile_values_current",
        "lead_profile_values",
        ["tenant_id", "lead_id", "field"],
        unique=True,
        postgresql_where=sa.text("is_current IS true"),
    )
    op.create_table(
        "pending_questions",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("target_field", sa.String(length=80), nullable=False),
        sa.Column("question", sa.String(length=180), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(status = 'pending' AND consumed_at IS NULL AND cancelled_at IS NULL) OR (status = 'consumed' AND consumed_at IS NOT NULL AND cancelled_at IS NULL) OR (status = 'cancelled' AND consumed_at IS NULL AND cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)",
            name="ck_pending_questions_lifecycle",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'consumed', 'cancelled')", name="ck_pending_questions_status"
        ),
        sa.CheckConstraint(
            "char_length(question) BETWEEN 1 AND 180", name="ck_pending_questions_length"
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 100", name="ck_pending_questions_priority"),
        sa.CheckConstraint("version > 0", name="ck_pending_questions_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id", "lead_id"],
            ["conversations.tenant_id", "conversations.id", "conversations.lead_id"],
            name="fk_pending_questions_conversation",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_pending_questions_extraction",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_index(
        "uq_pending_questions_active",
        "pending_questions",
        ["tenant_id", "conversation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "qualification_evaluations",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("processing_version", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("policy_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("opportunity", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("eligibility", sa.String(length=40), nullable=False),
        sa.Column("state_recommendation", sa.String(length=40), nullable=True),
        sa.Column("engine_version", sa.String(length=80), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contributions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("penalties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effects", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("handoff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_information", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("cause", sa.String(length=40), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(contributions) = 'array'", name="ck_qualification_contributions"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dimensions) = 'array'", name="ck_qualification_dimensions"
        ),
        sa.CheckConstraint("jsonb_typeof(effects) = 'array'", name="ck_qualification_effects"),
        sa.CheckConstraint(
            "jsonb_typeof(explanation) = 'object'", name="ck_qualification_explanation"
        ),
        sa.CheckConstraint("jsonb_typeof(handoff) = 'object'", name="ck_qualification_handoff"),
        sa.CheckConstraint(
            "jsonb_typeof(missing_information) = 'array'", name="ck_qualification_missing"
        ),
        sa.CheckConstraint("jsonb_typeof(penalties) = 'array'", name="ck_qualification_penalties"),
        sa.CheckConstraint("policy_version > 0", name="ck_qualification_policy_version"),
        sa.CheckConstraint("processing_version > 0", name="ck_qualification_processing_version"),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_qualification_score"),
        sa.CheckConstraint("subtotal BETWEEN 0 AND 100", name="ck_qualification_subtotal"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id", "lead_id"],
            ["conversations.tenant_id", "conversations.id", "conversations.lead_id"],
            name="fk_qualification_conversation_lead",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_qualification_extraction",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "message_id", "conversation_id"],
            [
                "conversation_messages.tenant_id",
                "conversation_messages.id",
                "conversation_messages.conversation_id",
            ],
            name="fk_qualification_message",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint(
            "tenant_id", "extraction_execution_id", name="uq_qualification_extraction"
        ),
        sa.UniqueConstraint("tenant_id", "id", "lead_id", name="uq_qualification_identity"),
        sa.UniqueConstraint(
            "tenant_id", "message_id", "processing_version", name="uq_qualification_message_version"
        ),
    )
    op.create_index(
        "ix_qualification_lead_history",
        "qualification_evaluations",
        ["tenant_id", "lead_id", "evaluated_at"],
        unique=False,
    )
    op.create_table(
        "lead_profile_conflicts",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=80), nullable=False),
        sa.Column("previous_value_id", sa.UUID(), nullable=False),
        sa.Column("new_value_id", sa.UUID(), nullable=False),
        sa.Column("extraction_execution_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("resolution", sa.String(length=500), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'open' AND resolved_at IS NULL) OR (status = 'resolved' AND resolved_at IS NOT NULL AND resolution IS NOT NULL)",
            name="ck_profile_conflicts_resolution",
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name="ck_profile_conflicts_status"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "extraction_execution_id", "lead_id"],
            [
                "extraction_executions.tenant_id",
                "extraction_executions.id",
                "extraction_executions.lead_id",
            ],
            name="fk_profile_conflicts_extraction",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "new_value_id", "lead_id"],
            [
                "lead_profile_values.tenant_id",
                "lead_profile_values.id",
                "lead_profile_values.lead_id",
            ],
            name="fk_profile_conflicts_new",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "previous_value_id", "lead_id"],
            [
                "lead_profile_values.tenant_id",
                "lead_profile_values.id",
                "lead_profile_values.lead_id",
            ],
            name="fk_profile_conflicts_previous",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
        sa.UniqueConstraint(
            "tenant_id",
            "extraction_execution_id",
            "field",
            "new_value_id",
            name="uq_profile_conflicts_application",
        ),
    )
    op.create_index(
        "ix_profile_conflicts_open",
        "lead_profile_conflicts",
        ["tenant_id", "lead_id", "status"],
        unique=False,
    )
    op.add_column(
        "audit_events",
        sa.Column("category", sa.String(length=60), server_default="platform", nullable=False),
    )
    op.add_column("audit_events", sa.Column("causation_id", sa.UUID(), nullable=True))
    op.add_column(
        "audit_events",
        sa.Column(
            "schema_version", sa.String(length=40), server_default="audit-event.v1", nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_conversations_last_message",
        "conversations",
        "conversation_messages",
        ["tenant_id", "last_message_id", "id"],
        ["tenant_id", "id", "conversation_id"],
    )
    op.create_foreign_key(
        "fk_conversations_processing_message",
        "conversations",
        "conversation_messages",
        ["tenant_id", "processing_message_id", "id"],
        ["tenant_id", "id", "conversation_id"],
    )
    op.create_foreign_key(
        "fk_message_processing_extraction",
        "message_processing",
        "extraction_executions",
        ["tenant_id", "extraction_execution_id"],
        ["tenant_id", "id"],
    )
    op.create_foreign_key(
        "fk_message_processing_evaluation",
        "message_processing",
        "qualification_evaluations",
        ["tenant_id", "evaluation_id"],
        ["tenant_id", "id"],
    )
    op.create_foreign_key(
        "fk_leads_current_evaluation",
        "leads",
        "qualification_evaluations",
        ["tenant_id", "current_evaluation_id", "id"],
        ["tenant_id", "id", "lead_id"],
    )

    for table in TENANT_TABLES:
        op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        op.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
        op.execute(
            sa.text(
                f"CREATE POLICY {table}_tenant_isolation ON {table} "
                f"USING (tenant_id = {TENANT_SETTING}) "
                f"WITH CHECK (tenant_id = {TENANT_SETTING})"
            )
        )

    op.execute(
        sa.text(
            "CREATE FUNCTION prevent_append_only_mutation() RETURNS trigger "
            "LANGUAGE plpgsql AS $$ BEGIN "
            "RAISE EXCEPTION 'append-only relation cannot be modified'; "
            "END; $$"
        )
    )
    op.execute(
        sa.text(
            "CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events "
            "FOR EACH ROW EXECUTE FUNCTION prevent_append_only_mutation()"
        )
    )
    op.execute(
        sa.text(
            "CREATE TRIGGER qualification_evaluations_append_only "
            "BEFORE UPDATE OR DELETE ON qualification_evaluations "
            "FOR EACH ROW EXECUTE FUNCTION prevent_append_only_mutation()"
        )
    )

    op.execute(
        "GRANT SELECT, INSERT, UPDATE ON contacts, leads, conversations, "
        "conversation_messages, message_processing, contact_preferences, "
        "handoff_requests, pending_questions TO app_runtime"
    )
    op.execute(
        "GRANT SELECT ON extraction_executions, lead_profile_values, "
        "lead_profile_conflicts, lead_commercial_signals, "
        "qualification_evaluations, conversation_outbox_events TO app_runtime"
    )
    op.execute("GRANT INSERT ON conversation_outbox_events TO app_runtime")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE ON contacts, leads, conversations, "
        "conversation_messages, message_processing, extraction_executions, "
        "lead_profile_values, lead_profile_conflicts, lead_commercial_signals, "
        "contact_preferences, handoff_requests, pending_questions, "
        "conversation_outbox_events TO app_worker"
    )
    op.execute("GRANT SELECT, INSERT ON qualification_evaluations TO app_worker")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER qualification_evaluations_append_only ON qualification_evaluations")
    op.execute("DROP TRIGGER audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION prevent_append_only_mutation()")
    op.drop_constraint("fk_leads_current_evaluation", "leads", type_="foreignkey")
    op.drop_constraint(
        "fk_message_processing_evaluation",
        "message_processing",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_message_processing_extraction",
        "message_processing",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_conversations_processing_message",
        "conversations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_conversations_last_message",
        "conversations",
        type_="foreignkey",
    )
    op.drop_column("audit_events", "schema_version")
    op.drop_column("audit_events", "causation_id")
    op.drop_column("audit_events", "category")
    op.drop_index("ix_profile_conflicts_open", table_name="lead_profile_conflicts")
    op.drop_table("lead_profile_conflicts")
    op.drop_index("ix_qualification_lead_history", table_name="qualification_evaluations")
    op.drop_table("qualification_evaluations")
    op.drop_index(
        "uq_pending_questions_active",
        table_name="pending_questions",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("pending_questions")
    op.drop_index(
        "uq_profile_values_current",
        table_name="lead_profile_values",
        postgresql_where=sa.text("is_current IS true"),
    )
    op.drop_index("ix_profile_values_history", table_name="lead_profile_values")
    op.drop_table("lead_profile_values")
    op.drop_index("ix_commercial_signals_active", table_name="lead_commercial_signals")
    op.drop_table("lead_commercial_signals")
    op.drop_index(
        "uq_handoff_requests_active",
        table_name="handoff_requests",
        postgresql_where=sa.text("status IN ('requested', 'queued', 'assigned', 'accepted')"),
    )
    op.drop_table("handoff_requests")
    op.drop_index(
        "uq_contact_preferences_active",
        table_name="contact_preferences",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("contact_preferences")
    op.drop_table("extraction_executions")
    op.drop_index("ix_message_processing_claim", table_name="message_processing")
    op.drop_table("message_processing")
    op.drop_index("ix_conversation_messages_timeline", table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_table("conversations")
    op.drop_table("leads")
    op.drop_index("ix_conversation_outbox_claim", table_name="conversation_outbox_events")
    op.drop_table("conversation_outbox_events")
    op.drop_table("contacts")
    # ### end Alembic commands ###
